### ISSUE TITLE
Не работает с последней версией qmk_firmware от Feb 16, 2021

### ISSUE THREAD

**Issue by romanchikovboris** [klavarog/arbitrary_keycode#1]
1. В пункте 3 функция  bool process_rgb_matrix(uint16_t keycode, keyrecord_t *record) изменена на void process_rgb_matrix(uint8_t row, uint8_t col, bool pressed)
2. Аккорд CHORD(LCTL_T(KC_BSPC),  CMB_000, CMB_002), не работает. Так же не работает такая последовательность в макросе (пробовал по отдельности, тоже не работает):
press_arbitrary_keycode(LSFT_T(KC_B), true);
press_arbitrary_keycode(LSFT_T(KC_B), false);

Ссылка на коммит https://github.com/qmk/qmk_firmware/pull/11046/commits/b35caf094e9af1f30efc5977767dc0e2cd8fe8f6

**Comment by optozorax** [comment]
1. Ох, сложное изменение, надо будет подумать как работать с его учётом. Спасибо.
2. Каким именно образом он не работает?:
    * Не компилируется
    * Не нажимает

**Comment by romanchikovboris** [comment]
Спасибо за быстрый ответ.
Все скомпилировалось без проблем, но по факту не работает

Я пробовал добавить аккорды. Запрограммировал 2 аккорда 
  1. CHORD(LCTL_T(KC_BSPC),  CMB_000, CMB_002),
  2. CHORD(KC_DEL,  		  CMB_001, CMB_002)
Второй аккорд сработал, а первый нет. 

Дальше попробовал добавить функции (как отдельно, так и совместно) и они не сработали
press_arbitrary_keycode(LSFT_T(KC_B), true);
press_arbitrary_keycode(LSFT_T(KC_B), false);

Клавиатура Moonlander

**P.S. Не по теме**. 
В combo возможно описка в документации
_Сейчас:_
bool process_record_user(uint16_t key, keyrecord_t *record) {
  if (!combo_process_record(**keycode**, record)) 
_Возможно имелось ввиду:_
bool process_record_user(uint16_t key, keyrecord_t *record) {
  if (!combo_process_record(**key**, record))

**Comment by optozorax** [comment]
Что за макрос `LCTL_T`? Вижу его впервые. Я знаю только просто `LCTL` или просто `LSFT` (вместо `LSFT_T`). Может в них дело?

Можешь скинуть сюда результат `git diff` в директории qmk?

P.S. поправил ридмишку, спасибо.

**Comment by optozorax** [comment]
> Клавиатура Moonlander

В таком случае лучше использовать форк https://github.com/zsa/qmk_firmware как основу.

**Comment by romanchikovboris** [comment]
1. Да. Действительно в них было дело. Только разбираюсь с QMK и перепутал с обозначениями в keymap
2. Пункт 3. где функция bool _process_rgb_matrix(uint16_t keycode, keyrecord_t *record)_ я проигнорировал. Вроде нет никаких проблем с подсветкой, но, возможно, она появляется при определенных условиях 
3. `git diff` Это случайно не то, что я кидал выше?

**Comment by optozorax** [comment]
1. Круто, тогда, я думаю, можно закрывать данное ишью, когда я придумаю что делать с последней версией qmk и подсветкой в ней.
2. Проблемы с подсветкой заключаются в том, что при нажатии аккорда на подсветке будет нажиматься клавиша с позицией (0, 0), это если включить режим когда подсвечиваются последние нажатые клавиши. Если это не критично, то это можно не делать.
3. Если всё починилось, тогда ничего не надо, и это не то.

**Comment by romanchikovboris** [comment]
Спасибо за помощь! 

P.S. Отличная статья на optozorax. Прочитав ее я просто не смог жить с обычной клавой и перешел на Moonlander)

**Comment by optozorax** [comment]
@romanchikovboris приятно слышать что моя статья оказывает такое влияние!)
